### ISSUE TITLE
Wrong password while connecting to db (can not be turth)

### ISSUE THREAD

**Issue by goors** [cusspvz/rethinkdb-express-api-boilerplate#3]
Hi,

I can not connect to remote or local db. I am getting error:
<pre>
Entering slow growth mode
Fail to create a new connection for the connection pool. Error:{"msg":"Error 12:Wrong password","message":"Error 12:Wrong password.","isOperational":true}
</pre>

I get bunch of that errors. I know username and password are correct since i have some python and go application that are using same username/password combination.

This is config:
<pre>
export const thinky = Thinky({
  host: DB_HOST,
  port: DB_PORT,
  db: DB_NAME,
  user: DB_USER,
  pass: DB_PASS,
})
</pre>

**Comment by goors** [comment]
It is
`password: DB_PASS,`

instead of 
`pass: DB_PASS,`

**Comment by cusspvz** [comment]
Thanks!
