### ISSUE TITLE
Bunch of errors on post ReferenceError: hook is not defined 

### ISSUE THREAD

**Issue by goors** [cusspvz/rethinkdb-express-api-boilerplate#4]
So here it is for now:

1. `ReferenceError: hook is not defined `when trying to do post at
`await hook( 'before create write', req, body )`

2. If i remove hook then i am getting `model.create is not a function`
in here `const obj = await model.create( body )`

**Comment by goors** [comment]
When i put:

<pre>hook = async ( hk, ...args ) => {
    const { hooks } = this

    if ( hooks && typeof hooks[hk] == 'function' ) {
      await hooks[hk].apply( this, args )
    }

    // Save it for later, to allow multiple hooks
    // for ( let hookName in hooks ) {
    //   if ( hookName !== hk ) continue
    //
    //   await hooks[hookName].apply( this, args )
    // }
  }</pre>

in front of get, post and so on next error that i am getting is:

`model.create is not a function`

**Comment by goors** [comment]
Also for get, for example
when you say `/api/modelname/someid` app return `500 status` code with error:

`"The query did not find a document and returned null."`

So instead of returning null it does not return nothing just that error.

I am switching to some other boilerplate this one does not work.

**Comment by cusspvz** [comment]
I've fixed the error with the `POST` request. I've migrated this boilerplate to use Mongo instead, and since then, I wasn't able to work on this. But if you want to give it another shot, I would appreciate it. :)

**Comment by goors** [comment]
I dont want to use Mongo.

**Comment by goors** [comment]
But let me try one more time.

**Comment by goors** [comment]
I am getting again `TypeError: model.create is not a function`. I tried with your default boilerplate without adding anything.

**Comment by goors** [comment]
Any idea on why?

**Comment by goors** [comment]
Also for `get`

`TypeError: Cannot read property 'get' of undefined` on `const data = await model.get(id)`

**Comment by goors** [comment]
Also it is unclear what to put in the POST if you put in `Content-Type: application/json; charset=UTF-8` you get the error: `Unexpected token } in JSON at position 121`

So for mobile app what would you send in headers to this api?

**Comment by goors** [comment]
Ok I got this up and running. Problem was `.create` is `.insert` and then in json it must be clean meaning:
<pre>
{
"key":"value",
}</pre>

is incorrect since there is a "," comma

**Comment by cusspvz** [comment]
You've managed to get it working?

**Comment by goors** [comment]
Yes i did. All is good.

**Comment by cusspvz** [comment]
Nice!
