### ISSUE TITLE
How to add middlewares: [ parseToken ] to some routes and other not in same route space?

### ISSUE THREAD

**Issue by goors** [cusspvz/rethinkdb-express-api-boilerplate#6]
Simple:
<pre>
export const Companies = new Service({
  model: Company,
  endpoint: '/companies',
  //middlewares: [ parseToken ],
  custom: {
    <b>//need middleware here</b>
    async 'POST /in-radius' (req) {
      
      let { body: { lon, lat, distance, measure } } = req
      const companies = await Company.getCompaniesInRadius(lon, lat, distance, measure)

      return {companies: companies}
    },
    <b>//dont need middleware here</b>
    async 'GET /:id' (req) {

      const { params: { id } } = req

      const company = await Company.get(id).getJoin({get_category: true}).run()

      return company

    },

  },

})
</pre>

**Comment by cusspvz** [comment]
You just call the middleware function within the method using `nextAsync` util.
If you need a better approach and want to implement custom array of functions into the service builder, just PR it and I'ld be glad to accept it.

Sample:
```diff
+import nextAsync from '../../boilerplate/utils/next-async'

// ...


    async 'POST /in-radius' (req, res) {
+      // ensure we have a token
+      await nextAsync( parseToken( req, res ) )

      let { body: { lon, lat, distance, measure } } = req
      const companies = await Company.getCompaniesInRadius(lon, lat, distance, measure)

      return {companies: companies}
    },
```
