### ISSUE TITLE
problem with update query

### ISSUE THREAD

**Issue by goors** [cusspvz/rethinkdb-express-api-boilerplate#7]
I send to put to `/url/:id`

<pre>{
"some_key":"some_value"
}
</pre>

and get this error:

`ReqlDriverError: Unrecognized option some_key in update after:`

**Comment by cusspvz** [comment]
Could you please check if you're experiencing it with the changes I've posted?

I found a version with those changes, which is harassed with tests and being used on a production environment, so I suppose it is working. :)
